- id: prevent-commit-on-default
  name: Prevent a commit on the default branch
  description: |
    Prevent a commit on the default branch
    A Pull Request should be used
  entry: git-hooks/prevent-commit-on-default
  language: script
  stages: [ pre-commit ]
  minimum_pre_commit_version: 3.2.0
- id: prevent-out-of-sync-commit
  name: Prevent a commit on a out-of-sync branch
  description: |
    Prevent a commit on a out-of-sync branch
    A pull should be done first
  entry: git-hooks/prevent-out-of-sync-commit
  language: script
  stages: [ pre-commit ]
  minimum_pre_commit_version: 3.2.0
